export dotfiles="$HOME/dotfiles"

. "$dotfiles/bash/env"
. "$dotfiles/bash/config"
. "$dotfiles/bash/aliases"
. "$dotfiles/ruby/aliases"
. "$dotfiles/git/aliases"
. "$dotfiles/windows/microsoft/dotnet/aliases"
. "$dotfiles/windows/microsoft/system/aliases"
. "$dotfiles/dirb/dirb.sh"
